# Generated by Django 5.1.1 on 2024-09-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbb_popularity',
            new_name='imdb_popularity',
        ),
    ]
