# Generated by Django 5.1.1 on 2024-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_genre_created_at_remove_genre_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
